services:
  db:
    image: postgres:16-alpine
    container_name: finance-db
    environment:
      POSTGRES_DB: finance_db
      POSTGRES_USER: finance_admin
      POSTGRES_PASSWORD: 9mul3WIEevf_1ZP_mfwL5cS4ic3rZ2
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U finance_user -d finance_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finance-backend
    environment:
      SERVER_PORT: 8081
      DB_URL: jdbc:postgresql://db:5432/finance_db
      DB_USERNAME: finance_admin
      DB_PASSWORD: 9mul3WIEevf_1ZP_mfwL5cS4ic3rZ2
      JWT_SECRET: d1JuzitC9FPIxYsrSf1TIUXitgwmIwCeaUTAmSAUHU2Nef5RfvYDYH81L8Rt2iZ1
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: /api
    container_name: finance-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  pgdata:
